// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fitnessApi.Repository.Context;

#nullable disable

namespace fitnessApi.Migrations
{
    [DbContext(typeof(FitnessContext))]
    [Migration("20260208193348_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fitnessApi.Models.Entities.Exercicios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescricaoExercicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO_EXERCICIO");

                    b.Property<int>("MusculosId")
                        .HasColumnType("int")
                        .HasColumnName("MUSCULOS_ID");

                    b.Property<string>("NomeExercicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_EXERCICIO");

                    b.HasKey("Id");

                    b.HasIndex("MusculosId");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("fitnessApi.Models.Entities.GrupoMuscular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescricaoGrupo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO_GRUPO");

                    b.Property<string>("NomeGrupoMuscular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_GRUPO_MUSCULAR");

                    b.HasKey("Id");

                    b.ToTable("GruposMusculares");
                });

            modelBuilder.Entity("fitnessApi.Models.Entities.Musculos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FibraMuscular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIBRA_MUSCULAR");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FUNCAO");

                    b.Property<int>("GrupoMuscularId")
                        .HasColumnType("int")
                        .HasColumnName("GRUPO_MUSCULAR_ID");

                    b.Property<string>("MovimentoPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOVIMENTO_PRINCIPAL");

                    b.Property<string>("NomeMusculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_MUSCULO");

                    b.Property<string>("TipoTecido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_TECIDO");

                    b.HasKey("Id");

                    b.HasIndex("GrupoMuscularId");

                    b.ToTable("Musculos");
                });

            modelBuilder.Entity("fitnessApi.Models.Entities.Exercicios", b =>
                {
                    b.HasOne("fitnessApi.Models.Entities.Musculos", "Musculos")
                        .WithMany("Exercicios")
                        .HasForeignKey("MusculosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musculos");
                });

            modelBuilder.Entity("fitnessApi.Models.Entities.Musculos", b =>
                {
                    b.HasOne("fitnessApi.Models.Entities.GrupoMuscular", "GrupoMuscular")
                        .WithMany("Musculos")
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");
                });

            modelBuilder.Entity("fitnessApi.Models.Entities.GrupoMuscular", b =>
                {
                    b.Navigation("Musculos");
                });

            modelBuilder.Entity("fitnessApi.Models.Entities.Musculos", b =>
                {
                    b.Navigation("Exercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
