// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fitnessApi.Repository.Context;

#nullable disable

namespace fitnessApi.Migrations
{
    [DbContext(typeof(FitnessContext))]
    [Migration("20260208201324_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fitnessApi.Models.Entities.Exercicios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescricaoExercicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO_EXERCICIO");

                    b.Property<int>("MusculosId")
                        .HasColumnType("int")
                        .HasColumnName("MUSCULOS_ID");

                    b.Property<string>("NomeExercicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_EXERCICIO");

                    b.HasKey("Id");

                    b.HasIndex("MusculosId");

                    b.ToTable("Exercicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescricaoExercicio = "Deite-se em um banco plano com os pés apoiados no chão. Segure a barra com as mãos afastadas um pouco além da largura dos ombros, com pegada pronada. Desça a barra de forma controlada até tocar o peitoral, mantendo os cotovelos em ângulo de aproximadamente 45 graus em relação ao corpo. Empurre a barra de volta à posição inicial, estendendo completamente os braços. Mantenha as escápulas retraídas e o core ativado durante todo o movimento.",
                            MusculosId = 1,
                            NomeExercicio = "Supino Reto com Barra"
                        },
                        new
                        {
                            Id = 2,
                            DescricaoExercicio = "Deite-se em um banco plano segurando um halter em cada mão, com os braços estendidos acima do peito e as palmas das mãos voltadas uma para a outra (pegada neutra). Com uma ligeira flexão nos cotovelos, abra os braços lateralmente em um movimento de arco controlado até sentir um alongamento no peitoral. Retorne à posição inicial contraindo o peitoral, como se estivesse abraçando algo. Evite estender ou flexionar excessivamente os cotovelos durante o movimento e mantenha o controle na fase excêntrica.",
                            MusculosId = 1,
                            NomeExercicio = "Crucifixo com Halteres"
                        },
                        new
                        {
                            Id = 3,
                            DescricaoExercicio = "Posicione as mãos em uma superfície elevada (banco ou step) com os braços estendidos na largura dos ombros. Mantenha o corpo em linha reta dos pés à cabeça, com o core ativado. Desça o corpo de forma controlada, flexionando os cotovelos até o peito quase tocar a superfície. Empurre o corpo de volta à posição inicial. A inclinação reduz a carga e permite maior ênfase na porção superior do peitoral e no peitoral menor.",
                            MusculosId = 2,
                            NomeExercicio = "Flexão de Braço Inclinada"
                        },
                        new
                        {
                            Id = 4,
                            DescricaoExercicio = "Apoie-se nas barras paralelas com os braços estendidos e o corpo suspenso. Incline o tronco ligeiramente para frente (cerca de 30 graus) e mantenha os cotovelos levemente afastados do corpo. Desça de forma controlada flexionando os cotovelos até sentir alongamento no peitoral. Empurre o corpo de volta à posição inicial contraindo o peitoral. A inclinação do tronco e a abertura dos cotovelos enfatizam o trabalho do peitoral em relação ao tríceps.",
                            MusculosId = 2,
                            NomeExercicio = "Mergulho nas Paralelas (Foco Peitoral)"
                        },
                        new
                        {
                            Id = 5,
                            DescricaoExercicio = "Fique em pé segurando uma barra com as mãos na largura dos ombros e pegada pronada, com os braços estendidos à frente do corpo. Mantenha a coluna ereta e os ombros relaxados na posição inicial. Eleve os ombros em direção às orelhas contraindo o trapézio, sem dobrar os cotovelos. Mantenha a contração no topo por 1-2 segundos e depois desça os ombros de forma controlada. Evite rolar os ombros; o movimento deve ser vertical.",
                            MusculosId = 3,
                            NomeExercicio = "Encolhimento de Ombros com Barra"
                        },
                        new
                        {
                            Id = 6,
                            DescricaoExercicio = "Fique em pé segurando uma barra com pegada pronada, mãos afastadas na largura dos ombros ou ligeiramente mais próximas. Mantenha a coluna ereta e o core ativado. Puxe a barra verticalmente em direção ao queixo, elevando os cotovelos acima da linha dos ombros. Os cotovelos devem liderar o movimento, mantendo-se sempre acima das mãos. Desça a barra de forma controlada até a posição inicial. Este exercício trabalha principalmente as fibras superiores do trapézio e os deltoides.",
                            MusculosId = 3,
                            NomeExercicio = "Remada Alta com Barra"
                        },
                        new
                        {
                            Id = 7,
                            DescricaoExercicio = "Segure a barra com pegada pronada (palmas voltadas para frente) e as mãos afastadas um pouco além da largura dos ombros. Pendure-se com os braços completamente estendidos. Puxe o corpo para cima contraindo as costas até o queixo ultrapassar a barra ou o peito tocar a barra. Foque em puxar os cotovelos para baixo e para trás, contraindo as escápulas. Desça de forma controlada até a posição inicial. Se necessário, use assistência ou peso adicional conforme seu nível.",
                            MusculosId = 4,
                            NomeExercicio = "Barra Fixa (Pegada Pronada)"
                        },
                        new
                        {
                            Id = 8,
                            DescricaoExercicio = "Fique em pé segurando uma barra com pegada pronada, mãos afastadas além da largura dos ombros. Incline o tronco para frente mantendo as costas retas e os joelhos levemente flexionados, até o tronco ficar em ângulo de aproximadamente 45 graus. Deixe a barra pendurada com os braços estendidos. Puxe a barra em direção à parte inferior do abdômen, contraindo as escápulas e mantendo os cotovelos próximos ao corpo. Desça a barra de forma controlada. Evite arredondar as costas ou usar impulso do corpo.",
                            MusculosId = 4,
                            NomeExercicio = "Remada Curvada com Barra"
                        },
                        new
                        {
                            Id = 9,
                            DescricaoExercicio = "Sente-se no aparelho de remada baixa com os pés apoiados na plataforma e joelhos levemente flexionados. Segure o puxador triangular ou a barra reta com as mãos. Mantenha a coluna ereta e o peito para fora. Puxe o puxador em direção ao abdômen, focando em retrair as escápulas (aproximá-las da coluna). Mantenha os cotovelos próximos ao corpo e aperte as escápulas no final do movimento. Retorne de forma controlada, permitindo que as escápulas se afastem novamente.",
                            MusculosId = 5,
                            NomeExercicio = "Remada Sentada com Polia"
                        },
                        new
                        {
                            Id = 10,
                            DescricaoExercicio = "Deite-se de bruços em um banco inclinado ou fique em pé inclinando o tronco para frente. Segure um halter em cada mão com os braços pendurados e palmas voltadas uma para a outra. Mantenha uma ligeira flexão nos cotovelos. Eleve os braços lateralmente em movimento de arco até a altura dos ombros, focando em contrair as escápulas. Mantenha a contração no topo e desça de forma controlada. Este exercício trabalha intensamente os romboides e a porção posterior do deltoide.",
                            MusculosId = 5,
                            NomeExercicio = "Crucifixo Inverso com Halteres"
                        },
                        new
                        {
                            Id = 11,
                            DescricaoExercicio = "Posicione a barra nas costas, apoiada no trapézio (não no pescoço). Fique em pé com os pés afastados na largura dos ombros ou ligeiramente mais, com os dedos levemente voltados para fora. Mantenha o peito para cima e o core ativado. Inicie o movimento empurrando os quadris para trás e flexionando os joelhos, descendo até as coxas ficarem paralelas ao solo ou abaixo (profundidade completa). Mantenha os joelhos alinhados com a ponta dos pés. Empurre o chão com os pés para retornar à posição inicial, mantendo a coluna neutra durante todo o movimento.",
                            MusculosId = 6,
                            NomeExercicio = "Agachamento Livre com Barra"
                        },
                        new
                        {
                            Id = 12,
                            DescricaoExercicio = "Sente-se no aparelho de leg press com as costas e a cabeça bem apoiadas no encosto. Posicione os pés na plataforma afastados na largura dos ombros, com os calcanhares alinhados. Destrave o aparelho e desça a plataforma de forma controlada, flexionando os joelhos até formar um ângulo de aproximadamente 90 graus. Empurre a plataforma de volta estendendo as pernas, mas sem travar completamente os joelhos no topo. Mantenha os glúteos e as costas sempre em contato com o banco.",
                            MusculosId = 6,
                            NomeExercicio = "Leg Press 45°"
                        },
                        new
                        {
                            Id = 13,
                            DescricaoExercicio = "Deite-se de bruços na máquina flexora com os joelhos alinhados com o eixo de rotação do aparelho. Posicione os calcanhares sob o rolo acolchoado. Segure nas alças laterais e mantenha o quadril em contato com o banco. Flexione os joelhos trazendo os calcanhares em direção aos glúteos, contraindo os isquiotibiais. Mantenha a contração no topo por 1 segundo e desça de forma controlada. Evite arquear excessivamente a lombar durante o movimento.",
                            MusculosId = 7,
                            NomeExercicio = "Flexão de Pernas na Máquina (Mesa Flexora)"
                        },
                        new
                        {
                            Id = 14,
                            DescricaoExercicio = "Fique em pé segurando uma barra com pegada pronada, mãos na largura dos ombros, com a barra apoiada na frente das coxas. Mantenha os joelhos levemente flexionados (semiflexionados) e travados nesta posição. Incline o tronco para frente empurrando o quadril para trás, mantendo a coluna neutra (reta) durante todo o movimento. Desça a barra deslizando-a próxima às pernas até sentir alongamento nos isquiotibiais. Retorne à posição inicial contraindo os isquiotibiais e glúteos, empurrando o quadril para frente. Mantenha o core ativado.",
                            MusculosId = 7,
                            NomeExercicio = "Stiff com Barra (Levantamento Terra Romeno)"
                        },
                        new
                        {
                            Id = 15,
                            DescricaoExercicio = "Posicione-se em uma máquina de panturrilha em pé ou com uma barra nas costas, com a parte anterior dos pés (metatarsos) apoiados em um step ou plataforma elevada e os calcanhares suspensos. Mantenha as pernas estendidas (joelhos levemente flexionados). Desça os calcanhares o máximo possível para alongar a panturrilha. Em seguida, eleve os calcanhares o mais alto possível contraindo os gastrocnêmios, ficando na ponta dos pés. Mantenha a contração no topo por 1 segundo e desça de forma controlada.",
                            MusculosId = 8,
                            NomeExercicio = "Elevação de Panturrilha em Pé"
                        },
                        new
                        {
                            Id = 16,
                            DescricaoExercicio = "Sente-se no leg press e posicione apenas a parte anterior dos pés (metatarsos) na borda inferior da plataforma, deixando os calcanhares livres para moverem-se. Estenda as pernas quase completamente e destrave o aparelho. Deixe os calcanhares descerem em direção ao corpo para alongar as panturrilhas. Empurre a plataforma com a parte anterior dos pés, elevando os calcanhares o máximo possível. Mantenha a contração e retorne de forma controlada. Este exercício permite usar cargas mais pesadas.",
                            MusculosId = 8,
                            NomeExercicio = "Elevação de Panturrilha no Leg Press"
                        },
                        new
                        {
                            Id = 17,
                            DescricaoExercicio = "Sente-se na máquina de panturrilha sentado com os pés apoiados na plataforma e os joelhos sob as almofadas. Ajuste a almofada para que fique apoiada confortavelmente sobre as coxas. Destrave o aparelho e deixe os calcanhares descerem o máximo possível para alongar o sóleo. Eleve os calcanhares pressionando a parte anterior dos pés contra a plataforma, contraindo intensamente o sóleo. O movimento deve ser controlado tanto na subida quanto na descida.",
                            MusculosId = 9,
                            NomeExercicio = "Elevação de Panturrilha Sentado"
                        },
                        new
                        {
                            Id = 18,
                            DescricaoExercicio = "Fique em pé próximo a uma parede ou suporte para equilíbrio. Posicione a parte anterior de um pé em um step ou superfície elevada com o calcanhar suspenso. Mantenha o joelho dessa perna levemente flexionado (o que enfatiza o sóleo). A outra perna pode ficar relaxada ou cruzada atrás. Desça o calcanhar o máximo possível e depois eleve-o contraindo o sóleo. Faça o movimento completo e controlado. Execute todas as repetições de um lado antes de trocar.",
                            MusculosId = 9,
                            NomeExercicio = "Elevação de Panturrilha Unilateral"
                        },
                        new
                        {
                            Id = 19,
                            DescricaoExercicio = "Fique em pé ou sentado com a barra apoiada na altura dos ombros, pegada pronada com as mãos afastadas um pouco além da largura dos ombros. Mantenha o core ativado e a coluna ereta. Empurre a barra verticalmente acima da cabeça até a extensão completa dos braços, mantendo a barra alinhada sobre a cabeça e os ombros. Desça a barra de forma controlada até a posição inicial (altura do queixo/clavícula). Evite arquear excessivamente a lombar.",
                            MusculosId = 10,
                            NomeExercicio = "Desenvolvimento com Barra (Military Press)"
                        },
                        new
                        {
                            Id = 20,
                            DescricaoExercicio = "Fique em pé segurando um halter em cada mão ao lado do corpo, com as palmas voltadas para dentro. Mantenha os cotovelos levemente flexionados e travados nesta posição. Eleve os braços lateralmente em um movimento de arco até os halteres ficarem na altura dos ombros (ou ligeiramente abaixo). Os cotovelos devem estar no mesmo nível ou ligeiramente acima dos punhos. Mantenha a contração por 1 segundo e desça de forma controlada. Evite usar impulso ou balançar o corpo.",
                            MusculosId = 10,
                            NomeExercicio = "Elevação Lateral com Halteres"
                        },
                        new
                        {
                            Id = 21,
                            DescricaoExercicio = "Fique em pé com uma faixa elástica presa sob o pé ou em um ponto baixo. Segure a outra extremidade com a mão do mesmo lado. Mantenha o braço ao lado do corpo com o cotovelo levemente flexionado. Afaste o braço lateralmente até aproximadamente 30-45 graus (não mais alto que isso para focar no supraespinal). Execute o movimento de forma lenta e controlada, tanto na subida quanto na descida. Use carga leve e foque no controle.",
                            MusculosId = 11,
                            NomeExercicio = "Abdução com Elástico (Posição Neutra)"
                        },
                        new
                        {
                            Id = 22,
                            DescricaoExercicio = "Fique em pé segurando halteres leves ao lado do corpo. Posicione os braços cerca de 30 graus à frente do corpo (plano escapular). Mantenha os polegares apontados para cima e os cotovelos quase totalmente estendidos. Eleve os braços simultaneamente neste plano diagonal até aproximadamente a altura dos ombros. Desça de forma controlada. Este exercício é específico para o supraespinal e deve ser feito com carga leve e execução perfeita.",
                            MusculosId = 11,
                            NomeExercicio = "Scaption (Elevação no Plano Escapular)"
                        },
                        new
                        {
                            Id = 23,
                            DescricaoExercicio = "Fique em pé lateralmente a uma faixa elástica presa na altura da cintura. Segure a ponta do elástico com a mão mais distante da fixação. Mantenha o cotovelo flexionado a 90 graus e colado ao tronco. Partindo da posição com a mão próxima ao umbigo, gire externamente o antebraço afastando a mão do corpo, mantendo o cotovelo fixo no tronco. Retorne de forma controlada. O movimento deve ocorrer apenas no ombro.",
                            MusculosId = 12,
                            NomeExercicio = "Rotação Externa com Elástico"
                        },
                        new
                        {
                            Id = 24,
                            DescricaoExercicio = "Deite-se lateralmente em um banco com o braço de cima segurando um halter leve. Mantenha o cotovelo flexionado a 90 graus e apoiado ao longo do tronco. O antebraço deve começar apontando para baixo. Gire externamente o ombro elevando o halter em um arco até o antebraço ficar próximo da vertical. Mantenha o cotovelo sempre em contato com o tronco. Desça de forma controlada. Use peso leve e movimento controlado.",
                            MusculosId = 12,
                            NomeExercicio = "Rotação Externa Deitado com Halter"
                        },
                        new
                        {
                            Id = 25,
                            DescricaoExercicio = "Fique em pé segurando halteres leves com os braços ao lado do corpo. Flexione os cotovelos a 90 graus mantendo-os fixos junto ao tronco. As palmas devem estar voltadas para dentro inicialmente. Gire os antebraços para fora (rotação externa), afastando as mãos do corpo enquanto os cotovelos permanecem fixos. Retorne à posição inicial de forma controlada. O movimento é pequeno e isolado no ombro.",
                            MusculosId = 13,
                            NomeExercicio = "Rotação Externa em Pé com Halteres"
                        },
                        new
                        {
                            Id = 26,
                            DescricaoExercicio = "Posicione-se em frente a uma polia alta com uma corda ou puxador de corda anexado. Segure as extremidades da corda com pegada neutra. Dê alguns passos para trás para criar tensão. Puxe a corda em direção ao rosto, abrindo as mãos lateralmente e mantendo os cotovelos elevados acima da linha dos ombros. Foque em contrair as escápulas e girar externamente os ombros. Retorne de forma controlada. Este exercício trabalha o redondo menor, infraespinal e porção posterior do deltoide.",
                            MusculosId = 13,
                            NomeExercicio = "Face Pull (Puxada Facial)"
                        },
                        new
                        {
                            Id = 27,
                            DescricaoExercicio = "Fique em pé lateralmente a uma faixa elástica presa na altura da cintura. Segure a extremidade do elástico com a mão mais próxima da fixação. Mantenha o cotovelo flexionado a 90 graus e colado ao tronco. Partindo da posição com a mão afastada do corpo, gire internamente o ombro trazendo a mão em direção ao umbigo. Mantenha o cotovelo fixo no tronco. Retorne de forma controlada.",
                            MusculosId = 14,
                            NomeExercicio = "Rotação Interna com Elástico"
                        },
                        new
                        {
                            Id = 28,
                            DescricaoExercicio = "Deite-se lateralmente em um banco com o braço de baixo segurando um halter leve. Flexione o cotovelo a 90 graus e posicione o antebraço apontando para frente. Gire internamente o ombro elevando o halter em direção ao abdômen. O cotovelo permanece apoiado no banco. Desça de forma controlada. Este exercício isola o subescapular. Use peso leve e movimento preciso.",
                            MusculosId = 14,
                            NomeExercicio = "Rotação Interna Deitado com Halter"
                        },
                        new
                        {
                            Id = 29,
                            DescricaoExercicio = "Fique em pé segurando uma barra com pegada supinada (palmas para cima), mãos na largura dos ombros. Mantenha os cotovelos fixos ao lado do corpo e os braços estendidos. Flexione os cotovelos levantando a barra em direção aos ombros, contraindo o bíceps. Evite balançar o corpo ou mover os cotovelos para frente. Desça a barra de forma controlada até a extensão completa. Mantenha o core ativado para evitar compensação da lombar.",
                            MusculosId = 15,
                            NomeExercicio = "Rosca Direta com Barra"
                        },
                        new
                        {
                            Id = 30,
                            DescricaoExercicio = "Fique em pé ou sentado segurando um halter em cada mão ao lado do corpo com as palmas voltadas para dentro. Mantenha os cotovelos fixos ao lado do tronco. Flexione um cotovelo de cada vez, girando o antebraço (supinação) à medida que o halter sobe. No topo, a palma deve estar voltada para o ombro. Contraia o bíceps e desça de forma controlada enquanto inicia o movimento com o outro braço. Alterne os lados de forma contínua.",
                            MusculosId = 15,
                            NomeExercicio = "Rosca Alternada com Halteres"
                        },
                        new
                        {
                            Id = 31,
                            DescricaoExercicio = "Deite-se em um banco plano segurando uma barra ou halteres com os braços estendidos acima do peito, pegada pronada. Mantenha os cotovelos fixos apontando para cima e para frente. Flexione apenas os cotovelos, descendo a barra em direção à testa ou parte superior da cabeça de forma controlada. Estenda os cotovelos contraindo o tríceps para retornar à posição inicial. Os ombros permanecem estáticos; apenas os antebraços se movem.",
                            MusculosId = 16,
                            NomeExercicio = "Tríceps Testa (Skull Crusher)"
                        },
                        new
                        {
                            Id = 32,
                            DescricaoExercicio = "Fique em frente a uma polia alta com uma barra reta ou corda anexada. Segure o puxador com pegada pronada, mãos próximas. Mantenha os cotovelos fixos ao lado do corpo e flexionados a aproximadamente 90 graus. Empurre o puxador para baixo estendendo completamente os cotovelos, contraindo o tríceps. Mantenha a contração por 1 segundo e retorne de forma controlada. Os cotovelos não devem se mover; apenas os antebraços realizam o movimento.",
                            MusculosId = 16,
                            NomeExercicio = "Tríceps na Polia Alta (Pulley)"
                        },
                        new
                        {
                            Id = 33,
                            DescricaoExercicio = "Fique em pé ou sentado segurando um halter em cada mão ao lado do corpo com pegada neutra (palmas voltadas uma para a outra). Mantenha os cotovelos fixos ao lado do tronco. Flexione os cotovelos simultaneamente ou alternadamente, levantando os halteres em direção aos ombros sem girar os punhos (mantendo a pegada neutra). Contraia no topo e desça de forma controlada. Esta variação enfatiza o braquial e o braquiorradial.",
                            MusculosId = 17,
                            NomeExercicio = "Rosca Martelo com Halteres"
                        },
                        new
                        {
                            Id = 34,
                            DescricaoExercicio = "Fique em pé segurando uma barra com pegada pronada (palmas para baixo), mãos na largura dos ombros. Mantenha os cotovelos fixos ao lado do corpo. Flexione os cotovelos levantando a barra em direção aos ombros, mantendo a pegada pronada durante todo o movimento. Contraia o bíceps e o braquial no topo e desça de forma controlada. A pegada pronada aumenta o recrutamento do braquial e do braquiorradial.",
                            MusculosId = 17,
                            NomeExercicio = "Rosca Inversa com Barra"
                        },
                        new
                        {
                            Id = 35,
                            DescricaoExercicio = "Deite-se de costas com os joelhos flexionados e pés apoiados no chão. Coloque as mãos atrás da cabeça ou cruzadas sobre o peito. Contraia o abdômen e eleve a cabeça e os ombros do chão, enrolando o tronco superior em direção à pelve. O movimento vem da contração abdominal, não da tração do pescoço. Mantenha a contração no topo por 1 segundo e desça de forma controlada. A lombar permanece em contato com o solo.",
                            MusculosId = 18,
                            NomeExercicio = "Abdominal Supra (Crunch)"
                        },
                        new
                        {
                            Id = 36,
                            DescricaoExercicio = "Pendure-se em uma barra fixa com os braços estendidos e o corpo totalmente suspenso. Mantenha as pernas juntas e estendidas (ou levemente flexionadas se for iniciante). Contraia o abdômen e eleve as pernas à frente até ficarem paralelas ao solo ou mais alto. Foque em utilizar o abdômen para curvar a pelve e elevar as pernas, não apenas os flexores do quadril. Desça as pernas de forma controlada sem balançar o corpo.",
                            MusculosId = 18,
                            NomeExercicio = "Elevação de Pernas Suspensa"
                        },
                        new
                        {
                            Id = 37,
                            DescricaoExercicio = "Deite-se de costas com os joelhos flexionados. Coloque as mãos atrás da cabeça. Contraia o abdômen e eleve o tronco rotacionando-o para um lado, levando o cotovelo em direção ao joelho oposto. O movimento deve vir da rotação do tronco, contraindo o oblíquo. Retorne ao centro e repita para o outro lado. Alterne os lados ou complete todas as repetições de um lado antes de trocar.",
                            MusculosId = 19,
                            NomeExercicio = "Abdominal Oblíquo (Crunch Lateral)"
                        },
                        new
                        {
                            Id = 38,
                            DescricaoExercicio = "Deite-se lateralmente apoiando o corpo no antebraço e na lateral do pé. Eleve o quadril do chão até o corpo formar uma linha reta dos pés à cabeça. Mantenha o core contraído e o corpo alinhado, evitando que o quadril caia. Mantenha a posição isométrica pelo tempo determinado. Esta posição trabalha intensamente o oblíquo do lado que está apoiado no chão. Repita do outro lado.",
                            MusculosId = 19,
                            NomeExercicio = "Prancha Lateral (Side Plank)"
                        },
                        new
                        {
                            Id = 39,
                            DescricaoExercicio = "Deite-se de costas com as mãos atrás da cabeça e as pernas elevadas com os joelhos flexionados a 90 graus. Eleve os ombros do chão mantendo o core ativado. Execute um movimento de pedalar, estendendo uma perna enquanto a outra se aproxima do peito. Simultaneamente, gire o tronco levando o cotovelo oposto em direção ao joelho que está vindo. Alterne os lados de forma contínua e controlada, mantendo sempre o abdômen contraído.",
                            MusculosId = 20,
                            NomeExercicio = "Bicicleta no Ar"
                        },
                        new
                        {
                            Id = 40,
                            DescricaoExercicio = "Posicione-se lateralmente a uma polia alta com os pés afastados. Segure a alça ou corda com ambas as mãos. Com os braços estendidos, puxe o cabo diagonalmente através do corpo, rotacionando o tronco desde a posição alta e lateral até a posição baixa e oposta. O movimento deve vir da rotação do tronco, não apenas dos braços. Mantenha o core ativado e retorne de forma controlada. Complete as repetições de um lado antes de trocar.",
                            MusculosId = 20,
                            NomeExercicio = "Rotação de Tronco na Polia (Woodchop)"
                        },
                        new
                        {
                            Id = 41,
                            DescricaoExercicio = "Deite-se de bruços e apoie-se nos antebraços e dedos dos pés. Mantenha os cotovelos diretamente sob os ombros. Eleve o corpo do chão mantendo uma linha reta dos pés à cabeça. Contraia intensamente o core, puxando o umbigo em direção à coluna. Evite arquear ou elevar excessivamente o quadril. Mantenha a posição isométrica, respirando normalmente. Este exercício é fundamental para a ativação do transverso do abdome.",
                            MusculosId = 21,
                            NomeExercicio = "Prancha (Plank)"
                        },
                        new
                        {
                            Id = 42,
                            DescricaoExercicio = "Posicione-se de quatro apoios ou em pé. Expire todo o ar dos pulmões e, em seguida, puxe o umbigo fortemente em direção à coluna vertebral, como se estivesse tentando encostar o umbigo nas costas. Mantenha esta contração profunda do transverso por 10-30 segundos enquanto respira superficialmente pelo nariz. Relaxe e repita. Este exercício trabalha especificamente o transverso do abdome, o principal estabilizador da coluna.",
                            MusculosId = 21,
                            NomeExercicio = "Vacuum Abdominal"
                        },
                        new
                        {
                            Id = 43,
                            DescricaoExercicio = "Posicione a barra nas costas ou use halteres. Fique em pé com os pés afastados na largura dos ombros ou um pouco além. Desça empurrando o quadril para trás e flexionando os joelhos até as coxas ficarem abaixo do paralelo ao solo. Quanto maior a profundidade (respeitando sua mobilidade), maior a ativação dos glúteos. Mantenha o peito para cima e os joelhos alinhados com os pés. Empurre o chão com os calcanhares para subir, contraindo os glúteos no topo.",
                            MusculosId = 22,
                            NomeExercicio = "Agachamento Profundo"
                        },
                        new
                        {
                            Id = 44,
                            DescricaoExercicio = "Sente-se no chão com as costas apoiadas em um banco. Posicione uma barra com carga sobre o quadril (use uma almofada para conforto). Apoie os pés no chão afastados na largura dos quadris, com os joelhos flexionados. Empurre os quadris para cima contraindo intensamente os glúteos até o corpo formar uma linha reta dos joelhos aos ombros. Mantenha a contração no topo por 1-2 segundos e desça de forma controlada. Este é um dos melhores exercícios para isolamento do glúteo máximo.",
                            MusculosId = 22,
                            NomeExercicio = "Hip Thrust (Elevação Pélvica com Carga)"
                        },
                        new
                        {
                            Id = 45,
                            DescricaoExercicio = "Deite-se lateralmente com o corpo alinhado. Mantenha a perna de baixo flexionada para estabilidade e a perna de cima estendida. Eleve a perna de cima lateralmente mantendo-a alinhada com o corpo (não rotacione o quadril ou leve a perna para frente). Contraia o glúteo médio no topo do movimento e desça de forma controlada. Pode-se usar caneleiras ou faixa elástica para resistência. Complete todas as repetições de um lado antes de trocar.",
                            MusculosId = 23,
                            NomeExercicio = "Abdução de Quadril Lateral (Deitado)"
                        },
                        new
                        {
                            Id = 46,
                            DescricaoExercicio = "Posicione uma faixa elástica ao redor das coxas, acima dos joelhos. Fique em pé com os pés afastados na largura dos quadris e joelhos levemente flexionados (posição de meia agachamento). Mantenha o tronco ereto e o core ativado. Dê passos laterais mantendo tensão constante na faixa, afastando e aproximando os pés sem deixar a tensão diminuir. O movimento deve ser controlado, contraindo o glúteo médio a cada passo. Execute passos em uma direção e depois retorne.",
                            MusculosId = 23,
                            NomeExercicio = "Caminhada Lateral com Faixa Elástica"
                        },
                        new
                        {
                            Id = 47,
                            DescricaoExercicio = "Sente-se na máquina de abdução de quadril com as costas apoiadas e as coxas posicionadas nos apoios almofadados. Mantenha os pés apoiados. Empurre os apoios lateralmente afastando as pernas o máximo possível, contraindo os glúteos. Mantenha a contração no final do movimento por 1 segundo e retorne de forma controlada. Evite usar impulso ou tirar as costas do encosto.",
                            MusculosId = 24,
                            NomeExercicio = "Abdução de Quadril na Máquina"
                        },
                        new
                        {
                            Id = 48,
                            DescricaoExercicio = "Deite-se lateralmente com os quadris e joelhos flexionados a aproximadamente 90 graus. Mantenha os pés juntos. Mantenha a pelve estável e abra o joelho de cima (abdução externa) afastando-o do joelho de baixo, como se estivesse abrindo uma concha. Contraia o glúteo médio e mínimo no topo do movimento. Desça de forma controlada mantendo os pés juntos. Pode-se usar faixa elástica ao redor dos joelhos para resistência adicional. Complete todas as repetições antes de trocar de lado.",
                            MusculosId = 24,
                            NomeExercicio = "Clamshell (Concha)"
                        },
                        new
                        {
                            Id = 49,
                            DescricaoExercicio = "Sente-se em um banco e apoie os antebraços nas coxas com as palmas das mãos voltadas para cima, segurando uma barra. Deixe os punhos pendurados além dos joelhos. Flexione os punhos levantando a barra o máximo possível contraindo os flexores do antebraço. Mantenha os antebraços totalmente apoiados. Desça a barra de forma controlada até alongar completamente os punhos. Execute o movimento de forma lenta e controlada.",
                            MusculosId = 25,
                            NomeExercicio = "Rosca de Punho com Barra (Palmas para Cima)"
                        },
                        new
                        {
                            Id = 50,
                            DescricaoExercicio = "Sente-se e apoie um antebraço na coxa com a palma voltada para cima, segurando um halter. Deixe o punho pendurado além do joelho. Flexione o punho levantando o halter contraindo os flexores. Mantenha o antebraço imóvel. Desça de forma controlada. Complete todas as repetições de um lado antes de trocar. O trabalho unilateral permite maior foco e amplitude de movimento.",
                            MusculosId = 25,
                            NomeExercicio = "Rosca de Punho Unilateral com Halter"
                        },
                        new
                        {
                            Id = 51,
                            DescricaoExercicio = "Fique em pé segurando um halter com uma mão em posição vertical (como se segurasse um martelo). Mantenha o antebraço ao lado do corpo ou apoiado em uma superfície. Mova o punho lateralmente em direção ao dedo mínimo (desvio ulnar), contraindo o flexor ulnar do carpo. Retorne à posição neutra de forma controlada. Este é um movimento de pequena amplitude mas muito específico.",
                            MusculosId = 26,
                            NomeExercicio = "Desvio Ulnar com Halter"
                        },
                        new
                        {
                            Id = 52,
                            DescricaoExercicio = "Sente-se e apoie os antebraços nas coxas com as palmas voltadas para baixo, segurando uma barra. Deixe os punhos pendurados além dos joelhos. Estenda os punhos levantando a barra dorsalmente. Este movimento trabalha os extensores principalmente, mas ao retornar à posição inicial com controle, há trabalho excêntrico e isométrico dos flexores, incluindo o flexor ulnar do carpo.",
                            MusculosId = 26,
                            NomeExercicio = "Rosca de Punho Pronada (Ênfase Ulnar)"
                        },
                        new
                        {
                            Id = 53,
                            DescricaoExercicio = "Segure uma bola de apertar ou hand grip na mão. Aperte o objeto o mais forte possível contraindo todos os músculos flexores dos dedos e do antebraço. Mantenha a contração máxima por 3-5 segundos e depois relaxe completamente. Repita pelo número desejado de repetições. Este exercício trabalha todos os flexores dos dedos, incluindo o flexor superficial.",
                            MusculosId = 27,
                            NomeExercicio = "Preensão com Bola ou Hand Grip"
                        },
                        new
                        {
                            Id = 54,
                            DescricaoExercicio = "Segure uma barra com os dedos abertos (não com pegada completa) deixando a barra rolar até a ponta dos dedos. Em seguida, enrole os dedos trazendo a barra de volta à palma da mão, fechando o punho completamente. Este movimento isola a flexão dos dedos e trabalha intensamente o flexor superficial e profundo dos dedos. Execute de forma lenta e controlada.",
                            MusculosId = 27,
                            NomeExercicio = "Flexão de Dedos com Barra"
                        },
                        new
                        {
                            Id = 55,
                            DescricaoExercicio = "Pendure-se em uma barra fixa com pegada pronada ou supinada. Relaxe o corpo completamente deixando todo o peso pendurado, mas mantendo a pegada firme. Este exercício isométrico trabalha intensamente todos os flexores dos dedos, do punho e do antebraço, especialmente o flexor profundo dos dedos. Mantenha a posição pelo tempo determinado. Aumente progressivamente o tempo de suspensão.",
                            MusculosId = 28,
                            NomeExercicio = "Dead Hang (Suspensão na Barra)"
                        },
                        new
                        {
                            Id = 56,
                            DescricaoExercicio = "Segure um peso pesado em cada mão (halteres, kettlebells ou barras) ao lado do corpo com pegada firme. Mantenha o tronco ereto, ombros para trás e core ativado. Caminhe para frente mantendo a pegada firme durante todo o percurso. Este exercício trabalha a força de preensão e todos os músculos do antebraço, principalmente os flexores profundos dos dedos que mantêm a pegada firme sob carga.",
                            MusculosId = 28,
                            NomeExercicio = "Farmers Walk (Caminhada do Fazendeiro)"
                        },
                        new
                        {
                            Id = 57,
                            DescricaoExercicio = "Sente-se e apoie os antebraços nas coxas com as palmas voltadas para baixo, segurando uma barra. Deixe os punhos pendurados além dos joelhos. Estenda os punhos levantando a barra dorsalmente (para cima) o máximo possível, contraindo os extensores do antebraço. Mantenha os antebraços totalmente apoiados. Desça a barra de forma controlada. Este exercício trabalha todos os extensores do punho.",
                            MusculosId = 29,
                            NomeExercicio = "Extensão de Punho com Barra"
                        },
                        new
                        {
                            Id = 58,
                            DescricaoExercicio = "Fique em pé segurando um halter verticalmente (posição de martelo). Mantenha o antebraço estabilizado. Mova o punho lateralmente em direção ao polegar (desvio radial), contraindo o extensor radial longo do carpo. Retorne à posição neutra controladamente. O movimento é pequeno mas específico para os extensores radiais.",
                            MusculosId = 29,
                            NomeExercicio = "Desvio Radial com Halter"
                        },
                        new
                        {
                            Id = 59,
                            DescricaoExercicio = "Sente-se e apoie um antebraço na coxa com a palma voltada para baixo, segurando um halter. Deixe o punho pendurado além do joelho. Estenda o punho levantando o halter dorsalmente, contraindo os extensores. Mantenha o antebraço imóvel. Desça de forma controlada. O trabalho unilateral permite maior amplitude e foco nos extensores radiais.",
                            MusculosId = 30,
                            NomeExercicio = "Extensão de Punho Unilateral com Halter"
                        },
                        new
                        {
                            Id = 60,
                            DescricaoExercicio = "Fique em frente a uma polia baixa. Segure uma barra reta com pegada pronada (palmas para baixo). Mantenha os cotovelos próximos ao corpo e os antebraços paralelos ao solo. Estenda os punhos dorsalmente contraindo os extensores do antebraço. Retorne à posição inicial controladamente. A polia mantém tensão constante durante todo o movimento.",
                            MusculosId = 30,
                            NomeExercicio = "Rosca de Punho Invertida na Polia"
                        },
                        new
                        {
                            Id = 61,
                            DescricaoExercicio = "Sente-se e apoie os antebraços nas coxas com as palmas voltadas para baixo, segurando uma barra com pegada fechada (mãos próximas). Deixe os punhos pendurados além dos joelhos. Estenda os punhos levantando a barra dorsalmente. A pegada fechada enfatiza mais o extensor ulnar do carpo. Desça de forma controlada.",
                            MusculosId = 31,
                            NomeExercicio = "Extensão de Punho com Pegada Fechada"
                        },
                        new
                        {
                            Id = 62,
                            DescricaoExercicio = "Segure um halter em posição vertical. Apoie o antebraço em uma superfície com o punho livre. Estenda o punho dorsalmente e simultaneamente desvie em direção ulnar (lado do dedo mínimo). Este movimento combinado isola o extensor ulnar do carpo. Execute de forma lenta e controlada com peso moderado.",
                            MusculosId = 31,
                            NomeExercicio = "Extensão de Punho com Desvio Ulnar"
                        },
                        new
                        {
                            Id = 63,
                            DescricaoExercicio = "Coloque um elástico ao redor dos cinco dedos de uma mão com os dedos unidos. Abra os dedos contra a resistência do elástico, estendendo-os e afastando-os o máximo possível. Mantenha a extensão por 1 segundo e retorne controladamente. Este exercício trabalha especificamente o extensor dos dedos e é excelente para equilíbrio muscular e prevenção de lesões.",
                            MusculosId = 32,
                            NomeExercicio = "Extensão de Dedos com Elástico"
                        },
                        new
                        {
                            Id = 64,
                            DescricaoExercicio = "Apoie a mão espalmada sobre uma mesa ou superfície plana. Mantenha a palma em contato com a superfície. Eleve apenas os dedos, estendendo-os o máximo possível enquanto a palma permanece apoiada. Mantenha a extensão por 2-3 segundos e relaxe. Este exercício isométrico trabalha o extensor dos dedos sem necessidade de equipamento.",
                            MusculosId = 32,
                            NomeExercicio = "Extensão de Dedos na Mesa"
                        },
                        new
                        {
                            Id = 65,
                            DescricaoExercicio = "Sente-se e apoie o antebraço na coxa ou em um banco. Segure um halter com a mão em posição neutra (polegar para cima). Gire o antebraço internamente (pronação) até a palma ficar voltada para baixo. Contraia o pronador redondo durante o movimento. Retorne à posição neutra de forma controlada. O cotovelo deve permanecer fixo e apenas o antebraço gira.",
                            MusculosId = 33,
                            NomeExercicio = "Pronação com Halter"
                        },
                        new
                        {
                            Id = 66,
                            DescricaoExercicio = "Segure um bastão ou cabo de vassoura com peso fixado em apenas uma extremidade. Mantenha o antebraço em posição neutra horizontalmente. Gire o antebraço para dentro (pronação) controlando o peso que tenta girar o bastão. Este exercício cria resistência excêntrica e concêntrica para o pronador redondo. Execute de forma muito controlada.",
                            MusculosId = 33,
                            NomeExercicio = "Pronação com Bastão (Peso em uma Extremidade)"
                        },
                        new
                        {
                            Id = 67,
                            DescricaoExercicio = "Sente-se e apoie o antebraço na coxa ou em um banco. Segure um halter com a mão em posição pronada (palma para baixo). Gire o antebraço externamente (supinação) até a palma ficar voltada para cima. Contraia o supinador e o bíceps durante o movimento. Retorne à posição pronada de forma controlada. O cotovelo permanece fixo.",
                            MusculosId = 34,
                            NomeExercicio = "Supinação com Halter"
                        },
                        new
                        {
                            Id = 68,
                            DescricaoExercicio = "Segure um bastão com peso fixado em apenas uma extremidade. Mantenha o antebraço pronado horizontalmente. Gire o antebraço para fora (supinação) controlando o peso. Este exercício trabalha intensamente o supinador e o bíceps. A resistência do peso em desequilíbrio aumenta o desafio. Execute de forma lenta e controlada.",
                            MusculosId = 34,
                            NomeExercicio = "Supinação com Bastão (Peso em uma Extremidade)"
                        });
                });

            modelBuilder.Entity("fitnessApi.Models.Entities.GrupoMuscular", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescricaoGrupo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRICAO_GRUPO");

                    b.Property<string>("NomeGrupoMuscular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_GRUPO_MUSCULAR");

                    b.HasKey("Id");

                    b.ToTable("GruposMusculares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescricaoGrupo = "O grupo muscular do peito é composto por músculos como o peitoral maior e o peitoral menor, responsáveis por movimentos de adução, flexão e rotação do braço.",
                            NomeGrupoMuscular = "Peito"
                        },
                        new
                        {
                            Id = 2,
                            DescricaoGrupo = "O grupo muscular das costas inclui músculos como o latíssimo do dorso, trapézio e romboides, que desempenham um papel crucial na extensão, adução e rotação dos ombros.",
                            NomeGrupoMuscular = "Costas"
                        },
                        new
                        {
                            Id = 3,
                            DescricaoGrupo = "O grupo muscular das pernas é composto por músculos como quadríceps, isquiotibiais, glúteos e panturrilhas, responsáveis por movimentos de extensão, flexão e estabilidade durante atividades como caminhar, correr e agachar.",
                            NomeGrupoMuscular = "Pernas"
                        },
                        new
                        {
                            Id = 4,
                            DescricaoGrupo = "O grupo muscular dos ombros inclui músculos como deltoides, trapézio e manguito rotador, que são essenciais para movimentos de elevação, rotação e estabilidade dos braços.",
                            NomeGrupoMuscular = "Ombros"
                        },
                        new
                        {
                            Id = 5,
                            DescricaoGrupo = "O grupo muscular dos braços é composto por músculos como bíceps, tríceps e braquial, responsáveis por movimentos de flexão, extensão e rotação dos cotovelos.",
                            NomeGrupoMuscular = "Braços"
                        },
                        new
                        {
                            Id = 6,
                            DescricaoGrupo = "O grupo muscular do abdômen inclui músculos como reto abdominal, oblíquos e transverso do abdômen, que desempenham um papel crucial na flexão, rotação e estabilização do tronco.",
                            NomeGrupoMuscular = "Abdômen"
                        },
                        new
                        {
                            Id = 7,
                            DescricaoGrupo = "O grupo muscular dos glúteos é composto por músculos como glúteo máximo, médio e mínimo, responsáveis por movimentos de extensão, abdução e rotação do quadril, além de desempenharem um papel importante na estabilidade pélvica.",
                            NomeGrupoMuscular = "Glúteos"
                        },
                        new
                        {
                            Id = 8,
                            DescricaoGrupo = "O grupo muscular dos antebraços inclui músculos como flexores e extensores do punho, que são responsáveis por movimentos de flexão, extensão e rotação dos punhos e dedos.",
                            NomeGrupoMuscular = "Antebraços"
                        });
                });

            modelBuilder.Entity("fitnessApi.Models.Entities.Musculos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FibraMuscular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIBRA_MUSCULAR");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FUNCAO");

                    b.Property<int>("GrupoMuscularId")
                        .HasColumnType("int")
                        .HasColumnName("GRUPO_MUSCULAR_ID");

                    b.Property<string>("MovimentoPrincipal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOVIMENTO_PRINCIPAL");

                    b.Property<string>("NomeMusculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOME_MUSCULO");

                    b.Property<string>("TipoTecido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TIPO_TECIDO");

                    b.HasKey("Id");

                    b.HasIndex("GrupoMuscularId");

                    b.ToTable("Musculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FibraMuscular = "Tipo II (força e potência)",
                            Funcao = "Adução do braço, Rotação medial do úmero, Flexão do braço, Extensão do braço",
                            GrupoMuscularId = 1,
                            MovimentoPrincipal = "Adução horizontal, flexão e rotação interna do ombro",
                            NomeMusculo = "Peitoral Maior",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 2,
                            FibraMuscular = "Tipo I (estabilização)",
                            Funcao = "Abdução e depressão da escápula, Rotação inferior da escápula, Auxiliar na respiração",
                            GrupoMuscularId = 1,
                            MovimentoPrincipal = "Depressão e protração da escápula",
                            NomeMusculo = "Peitoral Menor",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 3,
                            FibraMuscular = "Tipo I (postura e estabilização)",
                            Funcao = "Elevação da escápula, Retração da escápula, Depressão da escápula, Rotação superior da escápula, Extensão e rotação da cabeça/pescoço",
                            GrupoMuscularId = 2,
                            MovimentoPrincipal = "Elevação, retração e rotação da escápula",
                            NomeMusculo = "Trapézio",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 4,
                            FibraMuscular = "Tipo II (força)",
                            Funcao = "Extensão do braço, Adução do braço, Rotação medial do úmero, Auxiliar na respiração",
                            GrupoMuscularId = 2,
                            MovimentoPrincipal = "Extensão, adução e rotação interna do ombro",
                            NomeMusculo = "Grande Dorsal (Latíssimo do Dorso)",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 5,
                            FibraMuscular = "Tipo I (estabilização postural)",
                            Funcao = "Retração da escápula, Elevação da escápula, Rotação inferior da escápula",
                            GrupoMuscularId = 2,
                            MovimentoPrincipal = "Retração e elevação da escápula",
                            NomeMusculo = "Romboides (Maior e Menor)",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 6,
                            FibraMuscular = "Tipo II (força e potência)",
                            Funcao = "Extensão do joelho, Flexão do quadril",
                            GrupoMuscularId = 3,
                            MovimentoPrincipal = "Extensão do joelho, flexão do quadril",
                            NomeMusculo = "Quadríceps Femoral",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 7,
                            FibraMuscular = "Tipo I e II (misto)",
                            Funcao = "Flexão do joelho, Extensão do quadril, Rotação medial e lateral da perna",
                            GrupoMuscularId = 3,
                            MovimentoPrincipal = "Flexão do joelho, extensão do quadril",
                            NomeMusculo = "Isquiotibiais",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 8,
                            FibraMuscular = "Tipo II (explosão)",
                            Funcao = "Flexão plantar do tornozelo, Flexão do joelho",
                            GrupoMuscularId = 3,
                            MovimentoPrincipal = "Flexão plantar, flexão do joelho",
                            NomeMusculo = "Gastrocnêmio",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 9,
                            FibraMuscular = "Tipo I (resistência e postura)",
                            Funcao = "Flexão plantar do tornozelo",
                            GrupoMuscularId = 3,
                            MovimentoPrincipal = "Flexão plantar",
                            NomeMusculo = "Sóleo",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 10,
                            FibraMuscular = "Tipo II (força)",
                            Funcao = "Abdução do braço, Flexão e rotação medial, Extensão e rotação lateral",
                            GrupoMuscularId = 4,
                            MovimentoPrincipal = "Abdução, flexão e extensão do ombro",
                            NomeMusculo = "Deltoide",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 11,
                            FibraMuscular = "Tipo I (estabilização)",
                            Funcao = "Abdução do ombro (primeiros 15-30°), Estabilização da articulação glenoumeral",
                            GrupoMuscularId = 4,
                            MovimentoPrincipal = "Abdução inicial e estabilização",
                            NomeMusculo = "Manguito Rotador - Supraespinal",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 12,
                            FibraMuscular = "Tipo I (estabilização)",
                            Funcao = "Rotação lateral do braço, Estabilização da articulação glenoumeral",
                            GrupoMuscularId = 4,
                            MovimentoPrincipal = "Rotação externa e estabilização",
                            NomeMusculo = "Manguito Rotador - Infraespinal",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 13,
                            FibraMuscular = "Tipo I (estabilização)",
                            Funcao = "Rotação lateral do braço, Adução do braço, Estabilização da articulação glenoumeral",
                            GrupoMuscularId = 4,
                            MovimentoPrincipal = "Rotação externa e estabilização",
                            NomeMusculo = "Manguito Rotador - Redondo Menor",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 14,
                            FibraMuscular = "Tipo I (estabilização)",
                            Funcao = "Rotação medial do braço, Adução do braço, Estabilização da articulação glenoumeral",
                            GrupoMuscularId = 4,
                            MovimentoPrincipal = "Rotação interna e estabilização",
                            NomeMusculo = "Manguito Rotador - Subescapular",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 15,
                            FibraMuscular = "Tipo II (força)",
                            Funcao = "Flexão do cotovelo, Supinação do antebraço, Flexão do ombro (auxiliar)",
                            GrupoMuscularId = 5,
                            MovimentoPrincipal = "Flexão do cotovelo, supinação",
                            NomeMusculo = "Bíceps Braquial",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 16,
                            FibraMuscular = "Tipo II (força)",
                            Funcao = "Extensão do cotovelo, Extensão e adução do ombro (cabeça longa)",
                            GrupoMuscularId = 5,
                            MovimentoPrincipal = "Extensão do cotovelo",
                            NomeMusculo = "Tríceps Braquial",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 17,
                            FibraMuscular = "Tipo II (força)",
                            Funcao = "Flexão do cotovelo (principal flexor)",
                            GrupoMuscularId = 5,
                            MovimentoPrincipal = "Flexão do cotovelo",
                            NomeMusculo = "Braquial",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 18,
                            FibraMuscular = "Tipo I e II (misto)",
                            Funcao = "Flexão do tronco, Compressão das vísceras abdominais, Expiração forçada",
                            GrupoMuscularId = 6,
                            MovimentoPrincipal = "Flexão do tronco",
                            NomeMusculo = "Reto Abdominal",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 19,
                            FibraMuscular = "Tipo I (postura)",
                            Funcao = "Flexão do tronco, Flexão lateral ipsilateral, Rotação contralateral, Compressão abdominal",
                            GrupoMuscularId = 6,
                            MovimentoPrincipal = "Flexão, rotação e inclinação lateral",
                            NomeMusculo = "Oblíquo Externo",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 20,
                            FibraMuscular = "Tipo I (postura)",
                            Funcao = "Flexão do tronco, Flexão lateral ipsilateral, Rotação ipsilateral, Compressão abdominal",
                            GrupoMuscularId = 6,
                            MovimentoPrincipal = "Flexão, rotação e inclinação lateral",
                            NomeMusculo = "Oblíquo Interno",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 21,
                            FibraMuscular = "Tipo I (estabilização)",
                            Funcao = "Compressão abdominal (principal), Estabilização da coluna lombar, Expiração forçada, Aumento da pressão intra-abdominal",
                            GrupoMuscularId = 6,
                            MovimentoPrincipal = "Estabilização do core, compressão abdominal",
                            NomeMusculo = "Transverso do Abdome",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 22,
                            FibraMuscular = "Tipo II (força e potência)",
                            Funcao = "Extensão do quadril (principal), Rotação lateral da coxa, Estabilização da pelve",
                            GrupoMuscularId = 7,
                            MovimentoPrincipal = "Extensão e rotação externa do quadril",
                            NomeMusculo = "Glúteo Máximo",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 23,
                            FibraMuscular = "Tipo I (estabilização)",
                            Funcao = "Abdução da coxa, Rotação medial da coxa (fibras anteriores), Estabilização da pelve durante a marcha",
                            GrupoMuscularId = 7,
                            MovimentoPrincipal = "Abdução e estabilização pélvica",
                            NomeMusculo = "Glúteo Médio",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 24,
                            FibraMuscular = "Tipo I (estabilização)",
                            Funcao = "Abdução da coxa, Rotação medial da coxa, Estabilização da pelve",
                            GrupoMuscularId = 7,
                            MovimentoPrincipal = "Abdução e rotação interna do quadril",
                            NomeMusculo = "Glúteo Mínimo",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 25,
                            FibraMuscular = "Tipo I (resistência)",
                            Funcao = "Flexão do punho, Abdução da mão (desvio radial)",
                            GrupoMuscularId = 8,
                            MovimentoPrincipal = "Flexão e desvio radial do punho",
                            NomeMusculo = "Flexor Radial do Carpo",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 26,
                            FibraMuscular = "Tipo I (resistência)",
                            Funcao = "Flexão do punho, Adução da mão (desvio ulnar)",
                            GrupoMuscularId = 8,
                            MovimentoPrincipal = "Flexão e desvio ulnar do punho",
                            NomeMusculo = "Flexor Ulnar do Carpo",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 27,
                            FibraMuscular = "Tipo I (resistência)",
                            Funcao = "Flexão das articulações interfalângicas proximais, Flexão do punho",
                            GrupoMuscularId = 8,
                            MovimentoPrincipal = "Flexão dos dedos e punho",
                            NomeMusculo = "Flexor Superficial dos Dedos",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 28,
                            FibraMuscular = "Tipo I (resistência)",
                            Funcao = "Flexão das articulações interfalângicas distais",
                            GrupoMuscularId = 8,
                            MovimentoPrincipal = "Flexão distal dos dedos",
                            NomeMusculo = "Flexor Profundo dos Dedos",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 29,
                            FibraMuscular = "Tipo I (resistência)",
                            Funcao = "Extensão do punho, Abdução da mão (desvio radial)",
                            GrupoMuscularId = 8,
                            MovimentoPrincipal = "Extensão e desvio radial do punho",
                            NomeMusculo = "Extensor Radial Longo do Carpo",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 30,
                            FibraMuscular = "Tipo I (resistência)",
                            Funcao = "Extensão do punho, Abdução da mão",
                            GrupoMuscularId = 8,
                            MovimentoPrincipal = "Extensão do punho",
                            NomeMusculo = "Extensor Radial Curto do Carpo",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 31,
                            FibraMuscular = "Tipo I (resistência)",
                            Funcao = "Extensão do punho, Adução da mão (desvio ulnar)",
                            GrupoMuscularId = 8,
                            MovimentoPrincipal = "Extensão e desvio ulnar do punho",
                            NomeMusculo = "Extensor Ulnar do Carpo",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 32,
                            FibraMuscular = "Tipo I (resistência)",
                            Funcao = "Extensão das articulações metacarpofalângicas, Extensão do punho",
                            GrupoMuscularId = 8,
                            MovimentoPrincipal = "Extensão dos dedos e punho",
                            NomeMusculo = "Extensor dos Dedos",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 33,
                            FibraMuscular = "Tipo I (resistência)",
                            Funcao = "Pronação do antebraço, Flexão do cotovelo (auxiliar)",
                            GrupoMuscularId = 8,
                            MovimentoPrincipal = "Pronação do antebraço",
                            NomeMusculo = "Pronador Redondo",
                            TipoTecido = "Muscular estriado esquelético"
                        },
                        new
                        {
                            Id = 34,
                            FibraMuscular = "Tipo I (resistência)",
                            Funcao = "Supinação do antebraço",
                            GrupoMuscularId = 8,
                            MovimentoPrincipal = "Supinação do antebraço",
                            NomeMusculo = "Supinador",
                            TipoTecido = "Muscular estriado esquelético"
                        });
                });

            modelBuilder.Entity("fitnessApi.Models.Entities.Exercicios", b =>
                {
                    b.HasOne("fitnessApi.Models.Entities.Musculos", "Musculos")
                        .WithMany("Exercicios")
                        .HasForeignKey("MusculosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musculos");
                });

            modelBuilder.Entity("fitnessApi.Models.Entities.Musculos", b =>
                {
                    b.HasOne("fitnessApi.Models.Entities.GrupoMuscular", "GrupoMuscular")
                        .WithMany("Musculos")
                        .HasForeignKey("GrupoMuscularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoMuscular");
                });

            modelBuilder.Entity("fitnessApi.Models.Entities.GrupoMuscular", b =>
                {
                    b.Navigation("Musculos");
                });

            modelBuilder.Entity("fitnessApi.Models.Entities.Musculos", b =>
                {
                    b.Navigation("Exercicios");
                });
#pragma warning restore 612, 618
        }
    }
}
